data/websites.json

- Nepal Police
- Supreme Court

Added Multiple Websites

---

data/websites.json

Added 18 websites, 7 provincial government, 11 others

Added 18 websites

---

data/websites.json

Please check those and merge it

2 Websites added

---

data/websites.json

Add Nepal Engineering Council, Department of Survey, Land Management and Training Center and Department of Mines and Geology.

adds NEC,DOS,LMTC and DOMG

---

.github/workflows/merge_response.yml
data/websites.json

This pull request properly orders the data in alphabetical order and also corrects some of the incorrect or changed information.

chore: proper ordering of data and data correction

---

data/websites.json

added details of District administration office of Rupandehi

DAO Rupandehi

---

data/websites.json

Government Website of TSC added.

Teachers Service Commission Added

---

data/websites.json

Added websites of Nepal Government Ministry of Home Affairs District Administration Office of two districts and maintain format in another DAO site data.

Updated all 77 District Administration Office

---

data/websites.json

The websites of General Post Office, Department of Postal Service and Department of Drug Administration under Ministry of Health are added.

Added Postal Service and Drug Administration Office

---

data/websites.json

Here there are two major sites for province government:
1. Official province portal
2. Office of Chief Minister and Council of Minister
In this PR, these two working sites of all province are included.
Removed two websites not ending with .gov.np
1. National Human Rights Commission "https://www.nhrcnepal.org/"
2. Nepal Rastra Bank "https://www.nrb.org.np/"

Added Office of Chief Minister and Council of Minister & Pradesh Portals

---

data/websites.json

- Added website of Central Law Library
- Added website of Department of Electricity Development
- Added website of Department of Electricity Development
- Added website of Nepal Agricultural Research Council
- Added website of Nepal Kanun Patrika

feat: add some gov websites

---

data/websites.json
src/App.vue

chore: syntax and search error fix

---

data/websites.json

- Added website of Film Development Board
- Added website of Public Procurement Monitoring Office

feat: add fdb and ppmo websites

---

data/websites.json

feat: add bhojpur and kataari municipalities official websites

---

data/websites.json

District Coordination Committee of Lumbini Zone are added

---

data/websites.json

feat: add some local gov websites

---

data/websites.json

feat: add Waling and Jaleshwor Municipalities websites

---

data/websites.json

feat: add putalibazar and ratnanagar municipalities official websites

---

index.html

feat: add github corner to the website

---

data/websites.json

added Ratuwamai Municipality's website

---

data/websites.json

feat: add kamalamai and khandbari municipalities official websites

---

data/websites.json

feat: add centralized mail system and ghorahi municipality official websites

---

data/websites.json

added some websites

---

data/websites.json

feat: add belbari and phungling municipalities official websites

---

.github/CODEOWNERS
data/websites.json

- [ ✔] Added a new website
Added new website of National Youth Council and solved merge conflicts.

National youth council

---

data/websites.json

Added Pokhara Metropolitan City's website and description in websites.json.

Added Pokhara Metropolitan City's Website 

---

data/websites.json

Added Information about "Bagmati Pradesh | Ministry of Economic Affairs and Planning, Bagmati Province", "Bagmati Pradesh | Ministry of Land Management, Agriculture & Cooperative", "Koshi Pradesh | Ministry of Land Management, Agriculture and Cooperatives"

added some goverment site

---

data/websites.json

This PR adds all the rural municipalities of Morang District.

feat: add all rural municipailites of morang

---

data/websites.json

 District Coordination Committee of Koshi Zone

---

data/websites.json

feat: add some municipalities official websites

---

data/websites.json

feat: add some municipalities websites

---

data/websites.json

District Coordination Committee of Janakpur Zone

---

data/websites.json

Added Sundarbazar Municipality's Website to websites.json

---

data/websites.json

Added the New Website of Kanakai Municipality of Jhapa.

Added Kanakai Municipality Website in JSON File
